### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by NikosAlexandris** [thaura/GreekOpenData#2]
For github (and maybe preferred for elsewhere too), create an README.md (that is a markdown file) and replace the current html file. Thanks for the work!

**Comment by tha-lis** [comment]
Hi Nikos,

Thanks for the feedback.
Currently both the authors are on much needed vacations, with limited internet connectivity. That said, the issue will take a bit longer to be corrected than it should.
Thanks for the understanding.

**Comment by tha-lis** [comment]
README.html has been updated and converted to .md
Do you consider the issue closed?
